### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by gdonisi**

### CODE REVIEW

**Review by JakeGonder — APPROVED** [review]

**Comment by estep248** [comment]
Thanks for the great work, you took a lot off work off our shoulders 😌. A big thanks for your contribution. We will happily include your translation in the next release 😄.

**Review by estep248 — COMMENTED** [review]
lgtm

**Review by Svobby98 — APPROVED** [review]

**Review by estep248 — APPROVED** [review]

**Comment by JakeGonder** [comment]
I added the backend support for the language on the dev branch, so you can try it out by building from dev, or wait until 1.3.7 will go live, probably in a week or so. Thanks again for the work.

**Comment by gdonisi** [comment]
Thank you. Also sorry for the target branch, I totally forgot 😅
Do you plan using a platform like Weblate or Crowdin to handle translations?

**Comment by JakeGonder** [comment]
> Thank you. Also sorry for the target branch, I totally forgot 😅

No worries, we appreciated the confidence of going straight for the master branch😅

> Do you plan using a platform like Weblate or Crowdin to handle translations?

We have never considered to use a platform like that, but seeing how difficult it is to manage multiple languages, it seems like a good idea. If you want you can create an issue proposing this, especially if you have experience with any of those platforms and can recommend how / where we should proceed with this.

**Comment by JakeGonder** [comment]
@gdonisi Sorry that this took so long, but I finally created a release including your translation! 1.3.7 should be live in F-Droid and the Playstore tomorrow.

**Pull request merged**
